module.exports={
    folder_app:'app',
    folder_models:'models',
    folder_routers:'routers',
    folder_schemas:'schemas',
    folder_validate:'validate',
    folder_configs:'configs',
    folder_controllers:'controllers',
}